### ISSUE TITLE
Optimize for search engines

### ISSUE THREAD

**Issue by Rinrin0413** [Rinrin0413/rinrin0413.github.io#50]
## ToDo

- [x] Fix the incorrect date of articles in search engine indexes
- [x] Add a Japanese period to some meta descriptions
- [x] Add a canonical URL to each page
- [x] Create a sitemap [#51]
- [x] The shadow element of the `Title` component to non- heading tag

See: https://developers.google.com/search/docs
