### ISSUE TITLE
Web Tools (`/tools`)

### ISSUE THREAD

**Issue by Rinrin0413** [Rinrin0413/rinrin0413.github.io#86]
Implement the Web Tools pages (`/tools`).

## ToDo

- [x] Implement the page.
    - [x] Implement the API endpoints. [#88]
- [x] Add a web tool.
- [x] Add to the `sitemap.xml`.
- [x] Write documentation for the new API endpoints.
- [x] Refactor the code.
    - [x] Integrate the tag-related systems for Blog and Web Tools. [#90]
    - [x] Integrate the non-tag-related systems for Blog, Web Tools, Projects and Creations -pages. (BTPC Integration) [#92]
- [x] Add one more another tool. [#94]
- [x] Final adjustments.

## Issues to fix

- [x] Tool `time-diff`:
    - [x] ~~The "additional days inputs" will be one day short if the end time is earlier than the start time.~~ Fixed on 893ed65e46d19570d3ec5278534a511096a00527.
    - [x] ~~Page overflowing on mobile.~~ Fixed on ac2818131ba0c1bf2025aac514d5365cd158f6c7.
